include:
  - compose-services.yaml

services:
  gsw:
    build:
      context: .
      dockerfile: cmd/Containerfile
    depends_on:
      influxdb:
        condition: service_started
      grafana:
        condition: service_started
    environment:
      - GSW_DATABASE_HOST_NAME=influxdb
      - GSW_TELEMETRY_CONFIG=data/config/backplane.yaml
    ports:
      - 11020:11020/udp
      - 13020:13020/udp
      - 12005:12005/udp
      - 12006:12006/udp
      - 12002:12002/udp
